import { Lightbulb, Target, Users, Coffee, Grid3x3, Calendar, Star, Trello, Map, Trophy, TrendingUp, AlertTriangle, GitBranch, Network, ArrowUpDown, BarChart3, Route } from "lucide-react";
import { CanvasElement } from "./Canvas";

export const templates = [
  {
    id: 'brainstorm',
    name: 'Brainstorming',
    description: 'Session de créativité avec zones d\'idées',
    icon: Lightbulb,
    color: '#FFE066',
    category: 'Créativité',
    imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-brainstorm',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Brainstorming',
        fontSize: 28,
      },
      {
        id: 'idea-area-1',
        type: 'sticky' as const,
        x: 100,
        y: 180,
        width: 180,
        height: 180,
        color: '#FFF59D',
        content: 'Idée 1',
        fontSize: 16,
      },
      {
        id: 'idea-area-2',
        type: 'sticky' as const,
        x: 320,
        y: 180,
        width: 180,
        height: 180,
        color: '#FFCC80',
        content: 'Idée 2',
        fontSize: 16,
      },
      {
        id: 'idea-area-3',
        type: 'sticky' as const,
        x: 540,
        y: 180,
        width: 180,
        height: 180,
        color: '#FFAB91',
        content: 'Idée 3',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'retro',
    name: 'Rétrospective',
    description: 'Analyse d\'équipe avec sections structurées',
    icon: Target,
    color: '#64B5F6',
    category: 'Agile',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=200&fit=crop',
    elements: [] as CanvasElement[],
  },
  {
    id: 'lean-coffee',
    name: 'Lean Coffee',
    description: 'Format de réunion structurée sans agenda fixe',
    icon: Coffee,
    color: '#8D6E63',
    category: 'Réunion',
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-lean',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Lean Coffee',
        fontSize: 28,
      },
      {
        id: 'to-discuss',
        type: 'rectangle' as const,
        x: 100,
        y: 180,
        width: 200,
        height: 300,
        color: '#FFE0B2',
        borderRadius: 8,
      },
      {
        id: 'discussing',
        type: 'rectangle' as const,
        x: 330,
        y: 180,
        width: 200,
        height: 300,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'discussed',
        type: 'rectangle' as const,
        x: 560,
        y: 180,
        width: 200,
        height: 300,
        color: '#C8E6C9',
        borderRadius: 8,
      },
      {
        id: 'label-discuss',
        type: 'text' as const,
        x: 120,
        y: 200,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'À discuter',
        fontSize: 16,
      },
      {
        id: 'label-discussing',
        type: 'text' as const,
        x: 350,
        y: 200,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'En discussion',
        fontSize: 16,
      },
      {
        id: 'label-discussed',
        type: 'text' as const,
        x: 580,
        y: 200,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'Discuté',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'raci',
    name: 'Matrice RACI',
    description: 'Clarification des rôles et responsabilités',
    icon: Grid3x3,
    color: '#9C27B0',
    category: 'Gestion',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-raci',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Matrice RACI',
        fontSize: 28,
      },
      {
        id: 'header-r',
        type: 'rectangle' as const,
        x: 250,
        y: 160,
        width: 120,
        height: 60,
        color: '#E1BEE7',
        borderRadius: 8,
      },
      {
        id: 'header-a',
        type: 'rectangle' as const,
        x: 380,
        y: 160,
        width: 120,
        height: 60,
        color: '#CE93D8',
        borderRadius: 8,
      },
      {
        id: 'header-c',
        type: 'rectangle' as const,
        x: 510,
        y: 160,
        width: 120,
        height: 60,
        color: '#BA68C8',
        borderRadius: 8,
      },
      {
        id: 'header-i',
        type: 'rectangle' as const,
        x: 640,
        y: 160,
        width: 120,
        height: 60,
        color: '#AB47BC',
        borderRadius: 8,
      },
      {
        id: 'label-r',
        type: 'text' as const,
        x: 260,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Responsible',
        fontSize: 14,
      },
      {
        id: 'label-a',
        type: 'text' as const,
        x: 390,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Accountable',
        fontSize: 14,
      },
      {
        id: 'label-c',
        type: 'text' as const,
        x: 520,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Consulted',
        fontSize: 14,
      },
      {
        id: 'label-i',
        type: 'text' as const,
        x: 650,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Informed',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'gantt',
    name: 'Diagramme de Gantt',
    description: 'Planification et suivi de projet',
    icon: Calendar,
    color: '#FF5722',
    category: 'Planning',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-gantt',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'Planning Projet - Gantt',
        fontSize: 28,
      },
      {
        id: 'timeline',
        type: 'rectangle' as const,
        x: 100,
        y: 180,
        width: 700,
        height: 300,
        color: '#FFF3E0',
        borderRadius: 8,
      },
      {
        id: 'phase1',
        type: 'rectangle' as const,
        x: 120,
        y: 220,
        width: 200,
        height: 40,
        color: '#FF7043',
        borderRadius: 6,
      },
      {
        id: 'phase2',
        type: 'rectangle' as const,
        x: 340,
        y: 280,
        width: 180,
        height: 40,
        color: '#FFA726',
        borderRadius: 6,
      },
      {
        id: 'phase3',
        type: 'rectangle' as const,
        x: 540,
        y: 340,
        width: 220,
        height: 40,
        color: '#FFCA28',
        borderRadius: 6,
      },
      {
        id: 'label-phase1',
        type: 'text' as const,
        x: 140,
        y: 230,
        width: 160,
        height: 20,
        color: '#FFFFFF',
        content: 'Phase 1: Conception',
        fontSize: 14,
      },
      {
        id: 'label-phase2',
        type: 'text' as const,
        x: 360,
        y: 290,
        width: 140,
        height: 20,
        color: '#FFFFFF',
        content: 'Phase 2: Développement',
        fontSize: 14,
      },
      {
        id: 'label-phase3',
        type: 'text' as const,
        x: 560,
        y: 350,
        width: 180,
        height: 20,
        color: '#FFFFFF',
        content: 'Phase 3: Livraison',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'moscow',
    name: 'Priorisation MoSCoW',
    description: 'Must have, Should have, Could have, Won\'t have',
    icon: Star,
    color: '#4CAF50',
    category: 'Priorisation',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-moscow',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Priorisation MoSCoW',
        fontSize: 28,
      },
      {
        id: 'must',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 180,
        height: 200,
        color: '#C8E6C9',
        borderRadius: 8,
      },
      {
        id: 'should',
        type: 'rectangle' as const,
        x: 310,
        y: 160,
        width: 180,
        height: 200,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'could',
        type: 'rectangle' as const,
        x: 520,
        y: 160,
        width: 180,
        height: 200,
        color: '#FFECB3',
        borderRadius: 8,
      },
      {
        id: 'wont',
        type: 'rectangle' as const,
        x: 730,
        y: 160,
        width: 180,
        height: 200,
        color: '#FFCDD2',
        borderRadius: 8,
      },
      {
        id: 'label-must',
        type: 'text' as const,
        x: 120,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Must Have',
        fontSize: 16,
      },
      {
        id: 'label-should',
        type: 'text' as const,
        x: 330,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Should Have',
        fontSize: 16,
      },
      {
        id: 'label-could',
        type: 'text' as const,
        x: 540,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Could Have',
        fontSize: 16,
      },
      {
        id: 'label-wont',
        type: 'text' as const,
        x: 750,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Won\'t Have',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'kanban',
    name: 'Kanban Board',
    description: 'Visualisation du flux de travail',
    icon: Trello,
    color: '#2196F3',
    category: 'Agile',
    imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400&h=200&fit=crop&sat=-100',
    elements: [
      {
        id: 'title-kanban',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Kanban Board',
        fontSize: 28,
      },
      {
        id: 'backlog',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 180,
        height: 350,
        color: '#E3F2FD',
        borderRadius: 8,
      },
      {
        id: 'todo',
        type: 'rectangle' as const,
        x: 310,
        y: 160,
        width: 180,
        height: 350,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'inprogress',
        type: 'rectangle' as const,
        x: 520,
        y: 160,
        width: 180,
        height: 350,
        color: '#FFE0B2',
        borderRadius: 8,
      },
      {
        id: 'done',
        type: 'rectangle' as const,
        x: 730,
        y: 160,
        width: 180,
        height: 350,
        color: '#C8E6C9',
        borderRadius: 8,
      },
      {
        id: 'label-backlog',
        type: 'text' as const,
        x: 120,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Backlog',
        fontSize: 16,
      },
      {
        id: 'label-todo',
        type: 'text' as const,
        x: 330,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'À faire',
        fontSize: 16,
      },
      {
        id: 'label-inprogress',
        type: 'text' as const,
        x: 540,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'En cours',
        fontSize: 16,
      },
      {
        id: 'label-done',
        type: 'text' as const,
        x: 750,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Terminé',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'user-story-mapping',
    name: 'User Story Mapping',
    description: 'Cartographie des parcours utilisateur',
    icon: Map,
    color: '#00BCD4',
    category: 'Product',
    imageUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-usm',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'User Story Mapping',
        fontSize: 28,
      },
      {
        id: 'activities',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 700,
        height: 60,
        color: '#B2EBF2',
        borderRadius: 8,
      },
      {
        id: 'backbone',
        type: 'rectangle' as const,
        x: 100,
        y: 240,
        width: 700,
        height: 80,
        color: '#80DEEA',
        borderRadius: 8,
      },
      {
        id: 'walking-skeleton',
        type: 'rectangle' as const,
        x: 100,
        y: 340,
        width: 700,
        height: 100,
        color: '#4DD0E1',
        borderRadius: 8,
      },
      {
        id: 'label-activities',
        type: 'text' as const,
        x: 120,
        y: 175,
        width: 200,
        height: 30,
        color: '#2D3748',
        content: 'Activités Utilisateur',
        fontSize: 16,
      },
      {
        id: 'label-backbone',
        type: 'text' as const,
        x: 120,
        y: 260,
        width: 200,
        height: 30,
        color: '#FFFFFF',
        content: 'Backbone (Stories)',
        fontSize: 16,
      },
      {
        id: 'label-skeleton',
        type: 'text' as const,
        x: 120,
        y: 370,
        width: 200,
        height: 30,
        color: '#FFFFFF',
        content: 'MVP / Release 1',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'okr',
    name: 'OKR (Objectives & Key Results)',
    description: 'Définition des objectifs et résultats clés',
    icon: Trophy,
    color: '#FF9800',
    category: 'Stratégie',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-okr',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'OKR Framework',
        fontSize: 28,
      },
      {
        id: 'objective1',
        type: 'rectangle' as const,
        x: 100,
        y: 180,
        width: 300,
        height: 80,
        color: '#FFE0B2',
        borderRadius: 8,
      },
      {
        id: 'kr1',
        type: 'rectangle' as const,
        x: 130,
        y: 280,
        width: 240,
        height: 50,
        color: '#FFCC80',
        borderRadius: 6,
      },
      {
        id: 'kr2',
        type: 'rectangle' as const,
        x: 130,
        y: 345,
        width: 240,
        height: 50,
        color: '#FFCC80',
        borderRadius: 6,
      },
      {
        id: 'label-obj',
        type: 'text' as const,
        x: 120,
        y: 205,
        width: 260,
        height: 30,
        color: '#2D3748',
        content: 'Objectif: Améliorer l\'expérience',
        fontSize: 16,
      },
      {
        id: 'label-kr1',
        type: 'text' as const,
        x: 150,
        y: 295,
        width: 200,
        height: 20,
        color: '#2D3748',
        content: 'KR1: +20% satisfaction',
        fontSize: 14,
      },
      {
        id: 'label-kr2',
        type: 'text' as const,
        x: 150,
        y: 360,
        width: 200,
        height: 20,
        color: '#2D3748',
        content: 'KR2: -30% temps réponse',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'kaizen',
    name: 'Kaizen / Amélioration Continue',
    description: 'Cycle d\'amélioration continue PDCA',
    icon: TrendingUp,
    color: '#009688',
    category: 'Qualité',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=200&fit=crop&sat=-50',
    elements: [
      {
        id: 'title-kaizen',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Kaizen - PDCA',
        fontSize: 28,
      },
      {
        id: 'plan',
        type: 'circle' as const,
        x: 150,
        y: 180,
        width: 150,
        height: 150,
        color: '#B2DFDB',
      },
      {
        id: 'do',
        type: 'circle' as const,
        x: 450,
        y: 180,
        width: 150,
        height: 150,
        color: '#80CBC4',
      },
      {
        id: 'check',
        type: 'circle' as const,
        x: 450,
        y: 380,
        width: 150,
        height: 150,
        color: '#4DB6AC',
      },
      {
        id: 'act',
        type: 'circle' as const,
        x: 150,
        y: 380,
        width: 150,
        height: 150,
        color: '#26A69A',
      },
      {
        id: 'label-plan',
        type: 'text' as const,
        x: 190,
        y: 240,
        width: 70,
        height: 30,
        color: '#2D3748',
        content: 'Plan',
        fontSize: 18,
      },
      {
        id: 'label-do',
        type: 'text' as const,
        x: 500,
        y: 240,
        width: 50,
        height: 30,
        color: '#FFFFFF',
        content: 'Do',
        fontSize: 18,
      },
      {
        id: 'label-check',
        type: 'text' as const,
        x: 485,
        y: 440,
        width: 80,
        height: 30,
        color: '#FFFFFF',
        content: 'Check',
        fontSize: 18,
      },
      {
        id: 'label-act',
        type: 'text' as const,
        x: 195,
        y: 440,
        width: 60,
        height: 30,
        color: '#FFFFFF',
        content: 'Act',
        fontSize: 18,
      },
    ] as CanvasElement[],
  },
  {
    id: 'eisenhower',
    name: 'Matrice d\'Eisenhower',
    description: 'Priorisation urgent vs important',
    icon: AlertTriangle,
    color: '#F44336',
    category: 'Priorisation',
    imageUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-eisenhower',
        type: 'text' as const,
        x: 250,
        y: 60,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'Matrice d\'Eisenhower',
        fontSize: 28,
      },
      {
        id: 'urgent-important',
        type: 'rectangle' as const,
        x: 400,
        y: 150,
        width: 250,
        height: 200,
        color: '#FFCDD2',
        borderRadius: 8,
      },
      {
        id: 'not-urgent-important',
        type: 'rectangle' as const,
        x: 100,
        y: 150,
        width: 250,
        height: 200,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'urgent-not-important',
        type: 'rectangle' as const,
        x: 400,
        y: 380,
        width: 250,
        height: 200,
        color: '#E1F5FE',
        borderRadius: 8,
      },
      {
        id: 'not-urgent-not-important',
        type: 'rectangle' as const,
        x: 100,
        y: 380,
        width: 250,
        height: 200,
        color: '#F5F5F5',
        borderRadius: 8,
      },
      {
        id: 'label-ui',
        type: 'text' as const,
        x: 420,
        y: 170,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Urgent & Important\n(Faire immédiatement)',
        fontSize: 14,
      },
      {
        id: 'label-nui',
        type: 'text' as const,
        x: 120,
        y: 170,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Important\n(Planifier)',
        fontSize: 14,
      },
      {
        id: 'label-uni',
        type: 'text' as const,
        x: 420,
        y: 400,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Urgent\n(Déléguer)',
        fontSize: 14,
      },
      {
        id: 'label-nuni',
        type: 'text' as const,
        x: 120,
        y: 400,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Ni urgent ni important\n(Éliminer)',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'pi-planning',
    name: 'PI Planning SAFe',
    description: 'Program Increment Planning pour SAFe',
    icon: GitBranch,
    color: '#3F51B5',
    category: 'SAFe',
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-pi',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'PI Planning - SAFe',
        fontSize: 28,
      },
      {
        id: 'team1',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 200,
        height: 300,
        color: '#C5CAE9',
        borderRadius: 8,
      },
      {
        id: 'team2',
        type: 'rectangle' as const,
        x: 330,
        y: 160,
        width: 200,
        height: 300,
        color: '#9FA8DA',
        borderRadius: 8,
      },
      {
        id: 'team3',
        type: 'rectangle' as const,
        x: 560,
        y: 160,
        width: 200,
        height: 300,
        color: '#7986CB',
        borderRadius: 8,
      },
      {
        id: 'label-team1',
        type: 'text' as const,
        x: 120,
        y: 180,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'Équipe 1',
        fontSize: 18,
      },
      {
        id: 'label-team2',
        type: 'text' as const,
        x: 350,
        y: 180,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'Équipe 2',
        fontSize: 18,
      },
      {
        id: 'label-team3',
        type: 'text' as const,
        x: 580,
        y: 180,
        width: 160,
        height: 30,
        color: '#FFFFFF',
        content: 'Équipe 3',
        fontSize: 18,
      },
      {
        id: 'sprint1',
        type: 'text' as const,
        x: 120,
        y: 230,
        width: 160,
        height: 25,
        color: '#2D3748',
        content: 'Sprint 1',
        fontSize: 14,
      },
      {
        id: 'sprint2',
        type: 'text' as const,
        x: 120,
        y: 280,
        width: 160,
        height: 25,
        color: '#2D3748',
        content: 'Sprint 2',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'ishikawa',
    name: 'Diagramme d\'Ishikawa',
    description: 'Analyse cause-effet (arête de poisson)',
    icon: Network,
    color: '#607D8B',
    category: 'Qualité',
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-ishikawa',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'Diagramme d\'Ishikawa',
        fontSize: 28,
      },
      {
        id: 'problem',
        type: 'rectangle' as const,
        x: 650,
        y: 280,
        width: 180,
        height: 80,
        color: '#CFD8DC',
        borderRadius: 8,
      },
      {
        id: 'label-problem',
        type: 'text' as const,
        x: 670,
        y: 305,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Problème',
        fontSize: 16,
      },
      {
        id: 'category1',
        type: 'text' as const,
        x: 150,
        y: 200,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Méthode',
        fontSize: 14,
      },
      {
        id: 'category2',
        type: 'text' as const,
        x: 350,
        y: 200,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Main d\'œuvre',
        fontSize: 14,
      },
      {
        id: 'category3',
        type: 'text' as const,
        x: 150,
        y: 430,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Matériel',
        fontSize: 14,
      },
      {
        id: 'category4',
        type: 'text' as const,
        x: 350,
        y: 430,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Milieu',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'value-stream',
    name: 'Value Stream Mapping',
    description: 'Cartographie de la chaîne de valeur pour analyser les flux',
    icon: ArrowUpDown,
    color: '#9C27B0',
    category: 'Lean',
    imageUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-vsm',
        type: 'text' as const,
        x: 300,
        y: 60,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Value Stream Mapping',
        fontSize: 28,
      },
      // Supplier
      {
        id: 'supplier',
        type: 'rectangle' as const,
        x: 100,
        y: 150,
        width: 120,
        height: 80,
        color: '#E1BEE7',
        borderRadius: 8,
      },
      {
        id: 'supplier-text',
        type: 'text' as const,
        x: 110,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Fournisseur',
        fontSize: 14,
      },
      // Process 1
      {
        id: 'process1',
        type: 'rectangle' as const,
        x: 280,
        y: 150,
        width: 120,
        height: 80,
        color: '#CE93D8',
        borderRadius: 8,
      },
      {
        id: 'process1-text',
        type: 'text' as const,
        x: 290,
        y: 165,
        width: 100,
        height: 20,
        color: '#2D3748',
        content: 'Étape 1',
        fontSize: 14,
      },
      {
        id: 'process1-time',
        type: 'text' as const,
        x: 290,
        y: 190,
        width: 100,
        height: 20,
        color: '#666',
        content: 'Temps: 2h',
        fontSize: 12,
      },
      // Process 2
      {
        id: 'process2',
        type: 'rectangle' as const,
        x: 460,
        y: 150,
        width: 120,
        height: 80,
        color: '#CE93D8',
        borderRadius: 8,
      },
      {
        id: 'process2-text',
        type: 'text' as const,
        x: 470,
        y: 165,
        width: 100,
        height: 20,
        color: '#2D3748',
        content: 'Étape 2',
        fontSize: 14,
      },
      {
        id: 'process2-time',
        type: 'text' as const,
        x: 470,
        y: 190,
        width: 100,
        height: 20,
        color: '#666',
        content: 'Temps: 1h',
        fontSize: 12,
      },
      // Customer
      {
        id: 'customer',
        type: 'rectangle' as const,
        x: 640,
        y: 150,
        width: 120,
        height: 80,
        color: '#E1BEE7',
        borderRadius: 8,
      },
      {
        id: 'customer-text',
        type: 'text' as const,
        x: 650,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Client',
        fontSize: 14,
      },
      // Info boxes
      {
        id: 'info1',
        type: 'sticky' as const,
        x: 280,
        y: 280,
        width: 120,
        height: 80,
        color: '#FFF9C4',
        content: 'Temps d\'attente\n15min',
        fontSize: 12,
      },
      {
        id: 'info2',
        type: 'sticky' as const,
        x: 460,
        y: 280,
        width: 120,
        height: 80,
        color: '#FFF9C4',
        content: 'Temps d\'attente\n10min',
        fontSize: 12,
      },
    ] as CanvasElement[],
  },
  {
    id: 'swot',
    name: 'Analyse SWOT',
    description: 'Matrice pour analyser Forces, Faiblesses, Opportunités, Menaces',
    icon: BarChart3,
    color: '#4CAF50',
    category: 'Stratégie',
    imageUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-swot',
        type: 'text' as const,
        x: 300,
        y: 60,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Analyse SWOT',
        fontSize: 28,
      },
      // Strengths (Forces)
      {
        id: 'strengths-box',
        type: 'rectangle' as const,
        x: 150,
        y: 150,
        width: 250,
        height: 200,
        color: '#A5D6A7',
        borderRadius: 8,
      },
      {
        id: 'strengths-title',
        type: 'text' as const,
        x: 160,
        y: 165,
        width: 230,
        height: 30,
        color: '#1B5E20',
        content: 'FORCES (Strengths)',
        fontSize: 16,
      },
      {
        id: 'strengths-content',
        type: 'text' as const,
        x: 160,
        y: 200,
        width: 230,
        height: 120,
        color: '#2D3748',
        content: '• Expertise technique\n• Équipe motivée\n• Innovation',
        fontSize: 13,
      },
      // Weaknesses (Faiblesses)
      {
        id: 'weaknesses-box',
        type: 'rectangle' as const,
        x: 450,
        y: 150,
        width: 250,
        height: 200,
        color: '#FFCCBC',
        borderRadius: 8,
      },
      {
        id: 'weaknesses-title',
        type: 'text' as const,
        x: 460,
        y: 165,
        width: 230,
        height: 30,
        color: '#BF360C',
        content: 'FAIBLESSES (Weaknesses)',
        fontSize: 16,
      },
      {
        id: 'weaknesses-content',
        type: 'text' as const,
        x: 460,
        y: 200,
        width: 230,
        height: 120,
        color: '#2D3748',
        content: '• Budget limité\n• Manque de ressources\n• Communication',
        fontSize: 13,
      },
      // Opportunities (Opportunités)
      {
        id: 'opportunities-box',
        type: 'rectangle' as const,
        x: 150,
        y: 380,
        width: 250,
        height: 200,
        color: '#BBDEFB',
        borderRadius: 8,
      },
      {
        id: 'opportunities-title',
        type: 'text' as const,
        x: 160,
        y: 395,
        width: 230,
        height: 30,
        color: '#0D47A1',
        content: 'OPPORTUNITÉS (Opportunities)',
        fontSize: 16,
      },
      {
        id: 'opportunities-content',
        type: 'text' as const,
        x: 160,
        y: 430,
        width: 230,
        height: 120,
        color: '#2D3748',
        content: '• Marché en croissance\n• Nouvelles technologies\n• Partenariats',
        fontSize: 13,
      },
      // Threats (Menaces)
      {
        id: 'threats-box',
        type: 'rectangle' as const,
        x: 450,
        y: 380,
        width: 250,
        height: 200,
        color: '#F8BBD0',
        borderRadius: 8,
      },
      {
        id: 'threats-title',
        type: 'text' as const,
        x: 460,
        y: 395,
        width: 230,
        height: 30,
        color: '#880E4F',
        content: 'MENACES (Threats)',
        fontSize: 16,
      },
      {
        id: 'threats-content',
        type: 'text' as const,
        x: 460,
        y: 430,
        width: 230,
        height: 120,
        color: '#2D3748',
        content: '• Concurrence accrue\n• Changements réglementaires\n• Risques économiques',
        fontSize: 13,
      },
    ] as CanvasElement[],
  },
  {
    id: 'roadmap',
    name: 'Roadmap Produit',
    description: 'Planification visuelle des étapes et jalons du projet',
    icon: Route,
    color: '#FF9800',
    category: 'Planification',
    imageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=400&h=200&fit=crop',
    elements: [
      {
        id: 'title-roadmap',
        type: 'text' as const,
        x: 300,
        y: 60,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Roadmap Produit',
        fontSize: 28,
      },
      // Q1
      {
        id: 'q1-label',
        type: 'text' as const,
        x: 150,
        y: 140,
        width: 120,
        height: 40,
        color: '#2D3748',
        content: 'T1 - 2024',
        fontSize: 18,
      },
      {
        id: 'q1-item1',
        type: 'rectangle' as const,
        x: 150,
        y: 190,
        width: 120,
        height: 60,
        color: '#FFECB3',
        borderRadius: 8,
      },
      {
        id: 'q1-item1-text',
        type: 'text' as const,
        x: 160,
        y: 205,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Phase de\nrecherche',
        fontSize: 12,
      },
      {
        id: 'q1-item2',
        type: 'rectangle' as const,
        x: 150,
        y: 270,
        width: 120,
        height: 60,
        color: '#FFE082',
        borderRadius: 8,
      },
      {
        id: 'q1-item2-text',
        type: 'text' as const,
        x: 160,
        y: 285,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Conception\ninitiale',
        fontSize: 12,
      },
      // Q2
      {
        id: 'q2-label',
        type: 'text' as const,
        x: 310,
        y: 140,
        width: 120,
        height: 40,
        color: '#2D3748',
        content: 'T2 - 2024',
        fontSize: 18,
      },
      {
        id: 'q2-item1',
        type: 'rectangle' as const,
        x: 310,
        y: 190,
        width: 120,
        height: 60,
        color: '#FFD54F',
        borderRadius: 8,
      },
      {
        id: 'q2-item1-text',
        type: 'text' as const,
        x: 320,
        y: 205,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Développement\nMVP',
        fontSize: 12,
      },
      {
        id: 'q2-item2',
        type: 'rectangle' as const,
        x: 310,
        y: 270,
        width: 120,
        height: 60,
        color: '#FFCA28',
        borderRadius: 8,
      },
      {
        id: 'q2-item2-text',
        type: 'text' as const,
        x: 320,
        y: 285,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Tests\ninternes',
        fontSize: 12,
      },
      // Q3
      {
        id: 'q3-label',
        type: 'text' as const,
        x: 470,
        y: 140,
        width: 120,
        height: 40,
        color: '#2D3748',
        content: 'T3 - 2024',
        fontSize: 18,
      },
      {
        id: 'q3-item1',
        type: 'rectangle' as const,
        x: 470,
        y: 190,
        width: 120,
        height: 60,
        color: '#FFC107',
        borderRadius: 8,
      },
      {
        id: 'q3-item1-text',
        type: 'text' as const,
        x: 480,
        y: 205,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Beta\npublique',
        fontSize: 12,
      },
      {
        id: 'q3-item2',
        type: 'rectangle' as const,
        x: 470,
        y: 270,
        width: 120,
        height: 60,
        color: '#FFB300',
        borderRadius: 8,
      },
      {
        id: 'q3-item2-text',
        type: 'text' as const,
        x: 480,
        y: 285,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Corrections\net ajustements',
        fontSize: 12,
      },
      // Q4
      {
        id: 'q4-label',
        type: 'text' as const,
        x: 630,
        y: 140,
        width: 120,
        height: 40,
        color: '#2D3748',
        content: 'T4 - 2024',
        fontSize: 18,
      },
      {
        id: 'q4-item1',
        type: 'rectangle' as const,
        x: 630,
        y: 190,
        width: 120,
        height: 140,
        color: '#FFA726',
        borderRadius: 8,
      },
      {
        id: 'q4-item1-text',
        type: 'text' as const,
        x: 640,
        y: 230,
        width: 100,
        height: 60,
        color: '#2D3748',
        content: 'Lancement\nofficial v1.0',
        fontSize: 14,
      },
      // Milestones
      {
        id: 'milestone1',
        type: 'star' as const,
        x: 150,
        y: 360,
        width: 30,
        height: 30,
        color: '#FFD700',
      },
      {
        id: 'milestone1-text',
        type: 'text' as const,
        x: 140,
        y: 395,
        width: 50,
        height: 20,
        color: '#2D3748',
        content: 'Kick-off',
        fontSize: 10,
      },
      {
        id: 'milestone2',
        type: 'star' as const,
        x: 360,
        y: 360,
        width: 30,
        height: 30,
        color: '#FFD700',
      },
      {
        id: 'milestone2-text',
        type: 'text' as const,
        x: 355,
        y: 395,
        width: 40,
        height: 20,
        color: '#2D3748',
        content: 'MVP',
        fontSize: 10,
      },
      {
        id: 'milestone3',
        type: 'star' as const,
        x: 680,
        y: 360,
        width: 30,
        height: 30,
        color: '#FFD700',
      },
      {
        id: 'milestone3-text',
        type: 'text' as const,
        x: 670,
        y: 395,
        width: 50,
        height: 20,
        color: '#2D3748',
        content: 'Launch',
        fontSize: 10,
      },
    ] as CanvasElement[],
  },
];
