import { Lightbulb, Target, Users, Coffee, Grid3x3, Calendar, Star, Trello, Map, Trophy, TrendingUp, AlertTriangle, GitBranch, Network } from "lucide-react";
import { CanvasElement } from "./Canvas";

export const templates = [
  {
    id: 'brainstorm',
    name: 'Brainstorming',
    description: 'Session de créativité avec zones d\'idées',
    icon: Lightbulb,
    color: '#FFE066',
    category: 'Créativité',
    elements: [
      {
        id: 'title-brainstorm',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Brainstorming',
        fontSize: 28,
      },
      {
        id: 'idea-area-1',
        type: 'sticky' as const,
        x: 100,
        y: 180,
        width: 180,
        height: 180,
        color: '#FFF59D',
        content: 'Idée 1',
        fontSize: 16,
      },
      {
        id: 'idea-area-2',
        type: 'sticky' as const,
        x: 320,
        y: 180,
        width: 180,
        height: 180,
        color: '#FFCC80',
        content: 'Idée 2',
        fontSize: 16,
      },
      {
        id: 'idea-area-3',
        type: 'sticky' as const,
        x: 540,
        y: 180,
        width: 180,
        height: 180,
        color: '#FFAB91',
        content: 'Idée 3',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'retro',
    name: 'Rétrospective',
    description: 'Analyse d\'équipe avec sections structurées',
    icon: Target,
    color: '#64B5F6',
    category: 'Agile',
    elements: [] as CanvasElement[],
  },
  {
    id: 'lean-coffee',
    name: 'Lean Coffee',
    description: 'Format de réunion structurée sans agenda fixe',
    icon: Coffee,
    color: '#8D6E63',
    category: 'Réunion',
    elements: [
      {
        id: 'title-lean',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Lean Coffee',
        fontSize: 28,
      },
      {
        id: 'to-discuss',
        type: 'rectangle' as const,
        x: 100,
        y: 180,
        width: 200,
        height: 300,
        color: '#FFE0B2',
        borderRadius: 8,
      },
      {
        id: 'discussing',
        type: 'rectangle' as const,
        x: 330,
        y: 180,
        width: 200,
        height: 300,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'discussed',
        type: 'rectangle' as const,
        x: 560,
        y: 180,
        width: 200,
        height: 300,
        color: '#C8E6C9',
        borderRadius: 8,
      },
      {
        id: 'label-discuss',
        type: 'text' as const,
        x: 120,
        y: 200,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'À discuter',
        fontSize: 16,
      },
      {
        id: 'label-discussing',
        type: 'text' as const,
        x: 350,
        y: 200,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'En discussion',
        fontSize: 16,
      },
      {
        id: 'label-discussed',
        type: 'text' as const,
        x: 580,
        y: 200,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'Discuté',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'raci',
    name: 'Matrice RACI',
    description: 'Clarification des rôles et responsabilités',
    icon: Grid3x3,
    color: '#9C27B0',
    category: 'Gestion',
    elements: [
      {
        id: 'title-raci',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Matrice RACI',
        fontSize: 28,
      },
      {
        id: 'header-r',
        type: 'rectangle' as const,
        x: 250,
        y: 160,
        width: 120,
        height: 60,
        color: '#E1BEE7',
        borderRadius: 8,
      },
      {
        id: 'header-a',
        type: 'rectangle' as const,
        x: 380,
        y: 160,
        width: 120,
        height: 60,
        color: '#CE93D8',
        borderRadius: 8,
      },
      {
        id: 'header-c',
        type: 'rectangle' as const,
        x: 510,
        y: 160,
        width: 120,
        height: 60,
        color: '#BA68C8',
        borderRadius: 8,
      },
      {
        id: 'header-i',
        type: 'rectangle' as const,
        x: 640,
        y: 160,
        width: 120,
        height: 60,
        color: '#AB47BC',
        borderRadius: 8,
      },
      {
        id: 'label-r',
        type: 'text' as const,
        x: 260,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Responsible',
        fontSize: 14,
      },
      {
        id: 'label-a',
        type: 'text' as const,
        x: 390,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Accountable',
        fontSize: 14,
      },
      {
        id: 'label-c',
        type: 'text' as const,
        x: 520,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Consulted',
        fontSize: 14,
      },
      {
        id: 'label-i',
        type: 'text' as const,
        x: 650,
        y: 175,
        width: 100,
        height: 30,
        color: '#2D3748',
        content: 'Informed',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'gantt',
    name: 'Diagramme de Gantt',
    description: 'Planification et suivi de projet',
    icon: Calendar,
    color: '#FF5722',
    category: 'Planning',
    elements: [
      {
        id: 'title-gantt',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'Planning Projet - Gantt',
        fontSize: 28,
      },
      {
        id: 'timeline',
        type: 'rectangle' as const,
        x: 100,
        y: 180,
        width: 700,
        height: 300,
        color: '#FFF3E0',
        borderRadius: 8,
      },
      {
        id: 'phase1',
        type: 'rectangle' as const,
        x: 120,
        y: 220,
        width: 200,
        height: 40,
        color: '#FF7043',
        borderRadius: 6,
      },
      {
        id: 'phase2',
        type: 'rectangle' as const,
        x: 340,
        y: 280,
        width: 180,
        height: 40,
        color: '#FFA726',
        borderRadius: 6,
      },
      {
        id: 'phase3',
        type: 'rectangle' as const,
        x: 540,
        y: 340,
        width: 220,
        height: 40,
        color: '#FFCA28',
        borderRadius: 6,
      },
      {
        id: 'label-phase1',
        type: 'text' as const,
        x: 140,
        y: 230,
        width: 160,
        height: 20,
        color: '#FFFFFF',
        content: 'Phase 1: Conception',
        fontSize: 14,
      },
      {
        id: 'label-phase2',
        type: 'text' as const,
        x: 360,
        y: 290,
        width: 140,
        height: 20,
        color: '#FFFFFF',
        content: 'Phase 2: Développement',
        fontSize: 14,
      },
      {
        id: 'label-phase3',
        type: 'text' as const,
        x: 560,
        y: 350,
        width: 180,
        height: 20,
        color: '#FFFFFF',
        content: 'Phase 3: Livraison',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'moscow',
    name: 'Priorisation MoSCoW',
    description: 'Must have, Should have, Could have, Won\'t have',
    icon: Star,
    color: '#4CAF50',
    category: 'Priorisation',
    elements: [
      {
        id: 'title-moscow',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Priorisation MoSCoW',
        fontSize: 28,
      },
      {
        id: 'must',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 180,
        height: 200,
        color: '#C8E6C9',
        borderRadius: 8,
      },
      {
        id: 'should',
        type: 'rectangle' as const,
        x: 310,
        y: 160,
        width: 180,
        height: 200,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'could',
        type: 'rectangle' as const,
        x: 520,
        y: 160,
        width: 180,
        height: 200,
        color: '#FFECB3',
        borderRadius: 8,
      },
      {
        id: 'wont',
        type: 'rectangle' as const,
        x: 730,
        y: 160,
        width: 180,
        height: 200,
        color: '#FFCDD2',
        borderRadius: 8,
      },
      {
        id: 'label-must',
        type: 'text' as const,
        x: 120,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Must Have',
        fontSize: 16,
      },
      {
        id: 'label-should',
        type: 'text' as const,
        x: 330,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Should Have',
        fontSize: 16,
      },
      {
        id: 'label-could',
        type: 'text' as const,
        x: 540,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Could Have',
        fontSize: 16,
      },
      {
        id: 'label-wont',
        type: 'text' as const,
        x: 750,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Won\'t Have',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'kanban',
    name: 'Kanban Board',
    description: 'Visualisation du flux de travail',
    icon: Trello,
    color: '#2196F3',
    category: 'Agile',
    elements: [
      {
        id: 'title-kanban',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Kanban Board',
        fontSize: 28,
      },
      {
        id: 'backlog',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 180,
        height: 350,
        color: '#E3F2FD',
        borderRadius: 8,
      },
      {
        id: 'todo',
        type: 'rectangle' as const,
        x: 310,
        y: 160,
        width: 180,
        height: 350,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'inprogress',
        type: 'rectangle' as const,
        x: 520,
        y: 160,
        width: 180,
        height: 350,
        color: '#FFE0B2',
        borderRadius: 8,
      },
      {
        id: 'done',
        type: 'rectangle' as const,
        x: 730,
        y: 160,
        width: 180,
        height: 350,
        color: '#C8E6C9',
        borderRadius: 8,
      },
      {
        id: 'label-backlog',
        type: 'text' as const,
        x: 120,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Backlog',
        fontSize: 16,
      },
      {
        id: 'label-todo',
        type: 'text' as const,
        x: 330,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'À faire',
        fontSize: 16,
      },
      {
        id: 'label-inprogress',
        type: 'text' as const,
        x: 540,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'En cours',
        fontSize: 16,
      },
      {
        id: 'label-done',
        type: 'text' as const,
        x: 750,
        y: 180,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Terminé',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'user-story-mapping',
    name: 'User Story Mapping',
    description: 'Cartographie des parcours utilisateur',
    icon: Map,
    color: '#00BCD4',
    category: 'Product',
    elements: [
      {
        id: 'title-usm',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'User Story Mapping',
        fontSize: 28,
      },
      {
        id: 'activities',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 700,
        height: 60,
        color: '#B2EBF2',
        borderRadius: 8,
      },
      {
        id: 'backbone',
        type: 'rectangle' as const,
        x: 100,
        y: 240,
        width: 700,
        height: 80,
        color: '#80DEEA',
        borderRadius: 8,
      },
      {
        id: 'walking-skeleton',
        type: 'rectangle' as const,
        x: 100,
        y: 340,
        width: 700,
        height: 100,
        color: '#4DD0E1',
        borderRadius: 8,
      },
      {
        id: 'label-activities',
        type: 'text' as const,
        x: 120,
        y: 175,
        width: 200,
        height: 30,
        color: '#2D3748',
        content: 'Activités Utilisateur',
        fontSize: 16,
      },
      {
        id: 'label-backbone',
        type: 'text' as const,
        x: 120,
        y: 260,
        width: 200,
        height: 30,
        color: '#FFFFFF',
        content: 'Backbone (Stories)',
        fontSize: 16,
      },
      {
        id: 'label-skeleton',
        type: 'text' as const,
        x: 120,
        y: 370,
        width: 200,
        height: 30,
        color: '#FFFFFF',
        content: 'MVP / Release 1',
        fontSize: 16,
      },
    ] as CanvasElement[],
  },
  {
    id: 'okr',
    name: 'OKR (Objectives & Key Results)',
    description: 'Définition des objectifs et résultats clés',
    icon: Trophy,
    color: '#FF9800',
    category: 'Stratégie',
    elements: [
      {
        id: 'title-okr',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'OKR Framework',
        fontSize: 28,
      },
      {
        id: 'objective1',
        type: 'rectangle' as const,
        x: 100,
        y: 180,
        width: 300,
        height: 80,
        color: '#FFE0B2',
        borderRadius: 8,
      },
      {
        id: 'kr1',
        type: 'rectangle' as const,
        x: 130,
        y: 280,
        width: 240,
        height: 50,
        color: '#FFCC80',
        borderRadius: 6,
      },
      {
        id: 'kr2',
        type: 'rectangle' as const,
        x: 130,
        y: 345,
        width: 240,
        height: 50,
        color: '#FFCC80',
        borderRadius: 6,
      },
      {
        id: 'label-obj',
        type: 'text' as const,
        x: 120,
        y: 205,
        width: 260,
        height: 30,
        color: '#2D3748',
        content: 'Objectif: Améliorer l\'expérience',
        fontSize: 16,
      },
      {
        id: 'label-kr1',
        type: 'text' as const,
        x: 150,
        y: 295,
        width: 200,
        height: 20,
        color: '#2D3748',
        content: 'KR1: +20% satisfaction',
        fontSize: 14,
      },
      {
        id: 'label-kr2',
        type: 'text' as const,
        x: 150,
        y: 360,
        width: 200,
        height: 20,
        color: '#2D3748',
        content: 'KR2: -30% temps réponse',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'kaizen',
    name: 'Kaizen / Amélioration Continue',
    description: 'Cycle d\'amélioration continue PDCA',
    icon: TrendingUp,
    color: '#009688',
    category: 'Qualité',
    elements: [
      {
        id: 'title-kaizen',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 300,
        height: 50,
        color: '#2D3748',
        content: 'Kaizen - PDCA',
        fontSize: 28,
      },
      {
        id: 'plan',
        type: 'circle' as const,
        x: 150,
        y: 180,
        width: 150,
        height: 150,
        color: '#B2DFDB',
      },
      {
        id: 'do',
        type: 'circle' as const,
        x: 450,
        y: 180,
        width: 150,
        height: 150,
        color: '#80CBC4',
      },
      {
        id: 'check',
        type: 'circle' as const,
        x: 450,
        y: 380,
        width: 150,
        height: 150,
        color: '#4DB6AC',
      },
      {
        id: 'act',
        type: 'circle' as const,
        x: 150,
        y: 380,
        width: 150,
        height: 150,
        color: '#26A69A',
      },
      {
        id: 'label-plan',
        type: 'text' as const,
        x: 190,
        y: 240,
        width: 70,
        height: 30,
        color: '#2D3748',
        content: 'Plan',
        fontSize: 18,
      },
      {
        id: 'label-do',
        type: 'text' as const,
        x: 500,
        y: 240,
        width: 50,
        height: 30,
        color: '#FFFFFF',
        content: 'Do',
        fontSize: 18,
      },
      {
        id: 'label-check',
        type: 'text' as const,
        x: 485,
        y: 440,
        width: 80,
        height: 30,
        color: '#FFFFFF',
        content: 'Check',
        fontSize: 18,
      },
      {
        id: 'label-act',
        type: 'text' as const,
        x: 195,
        y: 440,
        width: 60,
        height: 30,
        color: '#FFFFFF',
        content: 'Act',
        fontSize: 18,
      },
    ] as CanvasElement[],
  },
  {
    id: 'eisenhower',
    name: 'Matrice d\'Eisenhower',
    description: 'Priorisation urgent vs important',
    icon: AlertTriangle,
    color: '#F44336',
    category: 'Priorisation',
    elements: [
      {
        id: 'title-eisenhower',
        type: 'text' as const,
        x: 250,
        y: 60,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'Matrice d\'Eisenhower',
        fontSize: 28,
      },
      {
        id: 'urgent-important',
        type: 'rectangle' as const,
        x: 400,
        y: 150,
        width: 250,
        height: 200,
        color: '#FFCDD2',
        borderRadius: 8,
      },
      {
        id: 'not-urgent-important',
        type: 'rectangle' as const,
        x: 100,
        y: 150,
        width: 250,
        height: 200,
        color: '#FFF9C4',
        borderRadius: 8,
      },
      {
        id: 'urgent-not-important',
        type: 'rectangle' as const,
        x: 400,
        y: 380,
        width: 250,
        height: 200,
        color: '#E1F5FE',
        borderRadius: 8,
      },
      {
        id: 'not-urgent-not-important',
        type: 'rectangle' as const,
        x: 100,
        y: 380,
        width: 250,
        height: 200,
        color: '#F5F5F5',
        borderRadius: 8,
      },
      {
        id: 'label-ui',
        type: 'text' as const,
        x: 420,
        y: 170,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Urgent & Important\n(Faire immédiatement)',
        fontSize: 14,
      },
      {
        id: 'label-nui',
        type: 'text' as const,
        x: 120,
        y: 170,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Important\n(Planifier)',
        fontSize: 14,
      },
      {
        id: 'label-uni',
        type: 'text' as const,
        x: 420,
        y: 400,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Urgent\n(Déléguer)',
        fontSize: 14,
      },
      {
        id: 'label-nuni',
        type: 'text' as const,
        x: 120,
        y: 400,
        width: 210,
        height: 40,
        color: '#2D3748',
        content: 'Ni urgent ni important\n(Éliminer)',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'pi-planning',
    name: 'PI Planning SAFe',
    description: 'Program Increment Planning pour SAFe',
    icon: GitBranch,
    color: '#3F51B5',
    category: 'SAFe',
    elements: [
      {
        id: 'title-pi',
        type: 'text' as const,
        x: 300,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'PI Planning - SAFe',
        fontSize: 28,
      },
      {
        id: 'team1',
        type: 'rectangle' as const,
        x: 100,
        y: 160,
        width: 200,
        height: 300,
        color: '#C5CAE9',
        borderRadius: 8,
      },
      {
        id: 'team2',
        type: 'rectangle' as const,
        x: 330,
        y: 160,
        width: 200,
        height: 300,
        color: '#9FA8DA',
        borderRadius: 8,
      },
      {
        id: 'team3',
        type: 'rectangle' as const,
        x: 560,
        y: 160,
        width: 200,
        height: 300,
        color: '#7986CB',
        borderRadius: 8,
      },
      {
        id: 'label-team1',
        type: 'text' as const,
        x: 120,
        y: 180,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'Équipe 1',
        fontSize: 18,
      },
      {
        id: 'label-team2',
        type: 'text' as const,
        x: 350,
        y: 180,
        width: 160,
        height: 30,
        color: '#2D3748',
        content: 'Équipe 2',
        fontSize: 18,
      },
      {
        id: 'label-team3',
        type: 'text' as const,
        x: 580,
        y: 180,
        width: 160,
        height: 30,
        color: '#FFFFFF',
        content: 'Équipe 3',
        fontSize: 18,
      },
      {
        id: 'sprint1',
        type: 'text' as const,
        x: 120,
        y: 230,
        width: 160,
        height: 25,
        color: '#2D3748',
        content: 'Sprint 1',
        fontSize: 14,
      },
      {
        id: 'sprint2',
        type: 'text' as const,
        x: 120,
        y: 280,
        width: 160,
        height: 25,
        color: '#2D3748',
        content: 'Sprint 2',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
  {
    id: 'ishikawa',
    name: 'Diagramme d\'Ishikawa',
    description: 'Analyse cause-effet (arête de poisson)',
    icon: Network,
    color: '#607D8B',
    category: 'Qualité',
    elements: [
      {
        id: 'title-ishikawa',
        type: 'text' as const,
        x: 250,
        y: 80,
        width: 400,
        height: 50,
        color: '#2D3748',
        content: 'Diagramme d\'Ishikawa',
        fontSize: 28,
      },
      {
        id: 'problem',
        type: 'rectangle' as const,
        x: 650,
        y: 280,
        width: 180,
        height: 80,
        color: '#CFD8DC',
        borderRadius: 8,
      },
      {
        id: 'label-problem',
        type: 'text' as const,
        x: 670,
        y: 305,
        width: 140,
        height: 30,
        color: '#2D3748',
        content: 'Problème',
        fontSize: 16,
      },
      {
        id: 'category1',
        type: 'text' as const,
        x: 150,
        y: 200,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Méthode',
        fontSize: 14,
      },
      {
        id: 'category2',
        type: 'text' as const,
        x: 350,
        y: 200,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Main d\'œuvre',
        fontSize: 14,
      },
      {
        id: 'category3',
        type: 'text' as const,
        x: 150,
        y: 430,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Matériel',
        fontSize: 14,
      },
      {
        id: 'category4',
        type: 'text' as const,
        x: 350,
        y: 430,
        width: 120,
        height: 30,
        color: '#2D3748',
        content: 'Milieu',
        fontSize: 14,
      },
    ] as CanvasElement[],
  },
];
